#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width	2
bspc config window_gap      10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

# Colors {{{
bspc config normal_border_color '#282828'
bspc config active_border_color '#282828'
bspc config focused_border_color '#a89984'
# }}}
# Rules {{{
#bspc rule -a Steam follow=off
# }}}

# (re)start sxhkd
pgrep sxhkd && pkill -SIGUSR1 -x sxhkd || sxhkd &

# Launch polybar
$HOME/.config/polybar/launch.sh

