#!/bin/sh

sxhkd &

bspc config border_width	3
bspc config window_gap      15
bspc config top_padding 32

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focused_frame_opacity 0.1
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# color settings
bspc config normal_border_color '#504945'
bspc config active_border_color '#504945'
bspc config focused_border_color '#a89984'

bspc config pointer_modifier mod1

$HOME/.config/lemonbuddy/launch.sh

