#!/bin/sh

# Reload the old state if it exists
if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

# Monitor config
~/.config/bspwm/bspwm_monitors.sh &

bspc config remove_unplugged_monitors true

bspc config border_width	2
bspc config window_gap      15

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config focus_follows_pointer true
bspc config click_to_focus true
#bspc config pointer_modifier mod1
bspc config pointer_action2 none

# Colors {{{
bspc config normal_border_color '#282828'
bspc config active_border_color '#282828'
bspc config focused_border_color '#a89984'
# }}}
# Rules {{{
bspc rule -r '*'
bspc rule -a Oblogout state=fullscreen
bspc rule -a "LibreOffice 5.3" state=tiled
bspc rule -a Gsimplecal border=off
# }}}

# (re)start sxhkd
if pgrep sxhkd
then
    pkill -SIGUSR1 -x sxhkd
else
    sxhkd &
    LOCK=1  # Assume the only time this happens is bootup
fi

# Launch polybar
~/.config/polybar/launch.sh

# Lock the screen if we just launched
[[ $LOCK -eq 1 ]] && i3lock-krx

