#!/bin/sh

# Monitor config
~/.config/bspwm/bspwm_monitors.sh &

bspc config remove_unplugged_monitors true

bspc config border_width	2
bspc config window_gap      10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config pointer_modifier mod1

# Colors {{{
bspc config normal_border_color '#282828'
bspc config active_border_color '#282828'
bspc config focused_border_color '#a89984'
# }}}
# Rules {{{
bspc rule -a Oblogout state=fullscreen
#bspc rule -a Steam follow=off
# }}}

# (re)start sxhkd
pgrep sxhkd && pkill -SIGUSR1 -x sxhkd || sxhkd &

# Launch polybar
~/.config/polybar/launch.sh

