#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_origin_display        focused
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config window_border_radius         10
yabai -m config window_border_blur           off
yabai -m config active_window_border_color   0xffa89984
yabai -m config normal_window_border_color   0xff282828
yabai -m config insert_feedback_color        0xffa89984
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

# rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^kitty$" opacity=0.95

echo "yabai configuration loaded.."
