# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt +C #Forgot what this is for, but pretty sure it's important

alias tmux='tmux -2'
alias vi='vim'
#alias pip='sudo pip'
#alias gem='sudo gem'

alias py='python2 -m IPython'
alias py3='python3 -m IPython'

## Ease of use for apt
alias apt='sudo apt'
alias aptu='apt update'
alias apti='aptu && apt install'
alias aptug='aptu && apt upgrade'
alias aptr='apt remove --purge'
alias aptar='apt autoremove'
alias apts='apt search'

# Ease of use for yay
alias pac='yay'
alias pacs='pac -Ss'   # Search
alias paci='pac -Sy'   # Install
alias pacU='pac -Syu'  # Full upgrade
alias pacX='pac -Rns'  # Remove package
alias pacXO='pac -Cd'  # Remove orphan packages

setopt prompt_cr prompt_sp

if [[ "$COLORTERM" == "xfce4-terminal"  ]] ; then
  export TERM=xterm-256color
fi

# Fix awful ls color
export LS_COLORS="$LS_COLORS:ow=30;42"

# Laziness
alias mcd='mkdcd'

# Source helper stuff
source ${ZDOTDIR:-$HOME}/.zprezto/runcoms/autosrc/*.zsh

# Stop breaking the terminal when i press C-s
stty -ixon

# Setup anaconda
source /home/krx/tools/anaconda3/etc/profile.d/conda.sh

# Setup virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/dev
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
