# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt +C #Forgot what this is for, but pretty sure it's important

alias tmux='tmux -2'
alias vi='vim'
#alias pip='sudo pip'
#alias gem='sudo gem'

alias py='ipython2'
alias py3='ipython'

# RIP PACAUR {{{
## Ease of use for pacaur
#alias pac='pacaur'
#alias pacs='pac -Ss'   # Search
#alias paci='pac -Sy'   # Install
#alias pacU='pac -Syu'  # Full upgrade
#alias pacX='pac -Rns'  # Remove package
#alias pacXO='pacX $(pac -Qtdq)'  # Remove orphan packages
# }}}

# Ease of use for yay
alias pac='yay'
alias pacs='pac -Ss'   # Search
alias paci='pac -Sy'   # Install
alias pacU='pac -Syu'  # Full upgrade
alias pacX='pac -Rns'  # Remove package
alias pacXO='pac -Cd'  # Remove orphan packages

setopt prompt_cr prompt_sp

if [[ "$COLORTERM" == "xfce4-terminal"  ]] ; then
  export TERM=xterm-256color
fi

# Fix awful ls color
export LS_COLORS="$LS_COLORS:ow=30;42"

# Laziness
alias mcd='mkdcd'

# Source helper stuff
source ${ZDOTDIR:-$HOME}/.zprezto/runcoms/autosrc/*.zsh

# Stop breaking the terminal when i press C-s
stty -ixon
